// frontend/src/components/layout/CollapsibleHorizontalPanel.vue
<script setup lang="ts">
/**
 * CollapsibleHorizontalPanel.vue
 * Ported from: planning/UI/src/components/CollapsibleHorizontalPanel.tsx
 * 
 * Collapsible side panel with vertical label when collapsed.
 */
import ResizablePanel from './ResizablePanel.vue'

interface Props {
  isCollapsed: boolean
  side: 'left' | 'right'
  defaultWidth?: number
  minWidth?: number
  maxWidth?: number
  label: string
}

const _props = withDefaults(defineProps<Props>(), {
  defaultWidth: 320,
  minWidth: 280,
  maxWidth: 600,
})
void _props

const emit = defineEmits<{
  toggle: []
}>()
</script>

<template>
  <!-- Collapsed state -->
  <div
    v-if="isCollapsed"
    class="w-8 bg-slate-50 border-slate-200 flex-shrink-0"
    :class="side === 'left' ? 'border-r' : 'border-l'"
  >
    <button
      @click="emit('toggle')"
      class="h-full w-full hover:bg-slate-100 transition-colors flex items-center justify-center"
    >
      <span
        class="text-xs font-medium text-slate-600 whitespace-nowrap"
        style="writing-mode: vertical-rl; transform: rotate(180deg)"
      >
        {{ label }}
      </span>
    </button>
  </div>

  <!-- Expanded state -->
  <ResizablePanel
    v-else
    :side="side"
    :default-width="defaultWidth"
    :min-width="280"
    :max-width="600"
  >
    <slot />
  </ResizablePanel>
</template>

// planning/UI/src/components/CollapsibleHorizontalPanel.tsx
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { ReactNode } from 'react';

interface CollapsibleHorizontalPanelProps {
  children: ReactNode;
  isCollapsed: boolean;
  onToggle: () => void;
  side: 'left' | 'right' | 'middle';
  defaultWidth?: number;
  className?: string;
  label?: string;
}

export function CollapsibleHorizontalPanel({ 
  children, 
  isCollapsed,
  onToggle,
  defaultWidth = 320,
  side = 'left',
  className = '',
  label = 'Panel'
}: CollapsibleHorizontalPanelProps) {
  return (
    <div 
      className={`relative bg-white border-slate-200 transition-all duration-300 ${
        side === 'left' ? 'border-r' : side === 'right' ? 'border-l' : ''
      } ${className}`}
      style={{ 
        width: isCollapsed ? '32px' : `${defaultWidth}px`,
        flexShrink: 0
      }}
    >
      {/* Collapsed state - show rotated label */}
      {isCollapsed ? (
        <button
          onClick={onToggle}
          className={`h-full w-full bg-slate-50 hover:bg-slate-100 transition-colors flex items-center justify-center ${
            side === 'left' ? 'border-r' : 'border-l'
          } border-slate-200`}
        >
          <span className="text-xs font-medium text-slate-600 whitespace-nowrap" style={{ writingMode: 'vertical-rl', transform: 'rotate(180deg)' }}>
            {label}
          </span>
        </button>
      ) : null}

      {/* Content */}
      <div className={`h-full ${isCollapsed ? 'hidden' : 'block'}`}>
        {children}
      </div>
    </div>
  );
}
