// frontend/src/components/workflow/ConnectionLine.vue
<script setup lang="ts">
/**
 * ConnectionLine.vue
 * Ported from: planning/UI/src/components/ConnectionLine.tsx
 * 
 * SVG bezier curves connecting workflow nodes.
 */

interface Props {
  id: string
  sourceNode: any
  targetNode: any
  sourcePortIndex: number
  targetPortIndex: number
}

const props = defineProps<Props>()
const emit = defineEmits<{
  delete: [connectionId: string]
}>()

// Calculate connection path
const startX = (props.sourceNode.position?.x ?? props.sourceNode.x) + 280    // Node width
const startY = (props.sourceNode.position?.y ?? props.sourceNode.y) + 70 + props.sourcePortIndex * 28
const endX = (props.targetNode.position?.x ?? props.targetNode.x)
const endY = (props.targetNode.position?.y ?? props.targetNode.y) + 70 + props.targetPortIndex * 28

const pathD = `M ${startX} ${startY} C ${startX + 100} ${startY}, ${endX - 100} ${endY}, ${endX} ${endY}`
</script>

<template>
  <g class="group cursor-pointer" @click="emit('delete', id)">
    <!-- Invisible wider path for easier click detection -->
    <path
      :d="pathD"
      stroke="transparent"
      stroke-width="12"
      fill="none"
    />
    
    <!-- Visible connection line -->
    <path
      :d="pathD"
      stroke="#94a3b8"
      stroke-width="2"
      fill="none"
      class="group-hover:stroke-red-400 transition-colors"
    />
    
    <!-- Delete indicator on hover -->
    <circle
      :cx="(startX + endX) / 2"
      :cy="(startY + endY) / 2"
      r="8"
      fill="white"
      stroke="#ef4444"
      stroke-width="2"
      class="opacity-0 group-hover:opacity-100 transition-opacity"
    />
    <text
      :x="(startX + endX) / 2"
      :y="(startY + endY) / 2 + 4"
      text-anchor="middle"
      font-size="12"
      fill="#ef4444"
      class="opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none"
    >
      ×
    </text>
  </g>
</template>

// planning/UI/src/components/ConnectionLine.tsx
import { useState } from 'react';

interface ConnectionLineProps {
  id: string;
  sourceNode: any;
  targetNode: any;
  sourcePortIndex: number;
  targetPortIndex: number;
  onDelete: (id: string) => void;
}

export function ConnectionLine({ 
  id, 
  sourceNode, 
  targetNode, 
  sourcePortIndex, 
  targetPortIndex,
  onDelete 
}: ConnectionLineProps) {
  const [isHovered, setIsHovered] = useState(false);

  // Calculate port positions
  const startX = sourceNode.x + 280; // node width
  const startY = sourceNode.y + 70 + sourcePortIndex * 28; // header height + port spacing
  const endX = targetNode.x;
  const endY = targetNode.y + 70 + targetPortIndex * 28;

  // Calculate control points for bezier curve
  const controlPoint1X = startX + (endX - startX) * 0.5;
  const controlPoint2X = startX + (endX - startX) * 0.5;

  const pathD = `M ${startX} ${startY} C ${controlPoint1X} ${startY}, ${controlPoint2X} ${endY}, ${endX} ${endY}`;

  // Calculate midpoint for delete button
  const midX = (startX + endX) / 2;
  const midY = (startY + endY) / 2;

  return (
    <g>
      {/* Invisible thicker line for easier hovering */}
      <path
        d={pathD}
        stroke="transparent"
        strokeWidth="12"
        fill="none"
        onMouseEnter={() => setIsHovered(true)}
        onMouseLeave={() => setIsHovered(false)}
        style={{ cursor: 'pointer', pointerEvents: 'stroke' }}
      />
      
      {/* Visible line */}
      <path
        d={pathD}
        stroke={isHovered ? '#3b82f6' : '#64748b'}
        strokeWidth="2"
        fill="none"
        style={{ pointerEvents: 'none' }}
      />

      {/* Delete button on hover */}
      {isHovered && (
        <g>
          <circle
            cx={midX}
            cy={midY}
            r="10"
            fill="#ef4444"
            onClick={(e) => {
              e.stopPropagation();
              onDelete(id);
            }}
            style={{ cursor: 'pointer', pointerEvents: 'auto' }}
          />
          <line
            x1={midX - 4}
            y1={midY - 4}
            x2={midX + 4}
            y2={midY + 4}
            stroke="white"
            strokeWidth="2"
            style={{ pointerEvents: 'none' }}
          />
          <line
            x1={midX + 4}
            y1={midY - 4}
            x2={midX - 4}
            y2={midY + 4}
            stroke="white"
            strokeWidth="2"
            style={{ pointerEvents: 'none' }}
          />
        </g>
      )}
    </g>
  );
}
